// AUTO-GENERATED from VS Code Seti icon theme (extensions/theme-seti/icons/
// vs-seti-icon-theme.json). Dark variants only. Do not edit by hand.

export interface SetiDef {
  /** Glyph in the Seti icon font (PUA codepoint). */
  c: string
  /** Glyph color. */
  color: string
}

export const ICON_DEFS: Record<string, SetiDef> = {
  "_R": { c: '\uE001', color: "#519aba" },
  "_argdown": { c: '\uE003', color: "#519aba" },
  "_asm": { c: '\uE004', color: "#cc3e44" },
  "_audio": { c: '\uE005', color: "#a074c4" },
  "_babel": { c: '\uE006', color: "#cbcb41" },
  "_bazel": { c: '\uE007', color: "#8dc149" },
  "_bazel_1": { c: '\uE007', color: "#4d5a5e" },
  "_bicep": { c: '\uE008', color: "#519aba" },
  "_bower": { c: '\uE009', color: "#e37933" },
  "_bsl": { c: '\uE00A', color: "#cc3e44" },
  "_c": { c: '\uE00C', color: "#519aba" },
  "_c-sharp": { c: '\uE00B', color: "#519aba" },
  "_c_1": { c: '\uE00C', color: "#a074c4" },
  "_c_2": { c: '\uE00C', color: "#cbcb41" },
  "_cake": { c: '\uE00D', color: "#cc3e44" },
  "_cake_php": { c: '\uE00E', color: "#cc3e44" },
  "_clock": { c: '\uE012', color: "#519aba" },
  "_clock_1": { c: '\uE012', color: "#6d8086" },
  "_clojure": { c: '\uE013', color: "#8dc149" },
  "_clojure_1": { c: '\uE013', color: "#519aba" },
  "_code-climate": { c: '\uE014', color: "#8dc149" },
  "_code-search": { c: '\uE015', color: "#a074c4" },
  "_coffee": { c: '\uE016', color: "#cbcb41" },
  "_coldfusion": { c: '\uE018', color: "#519aba" },
  "_config": { c: '\uE019', color: "#6d8086" },
  "_cpp": { c: '\uE01A', color: "#519aba" },
  "_cpp_1": { c: '\uE01A', color: "#a074c4" },
  "_cpp_2": { c: '\uE01A', color: "#cbcb41" },
  "_crystal": { c: '\uE01B', color: "#d4d7d6" },
  "_crystal_embedded": { c: '\uE01C', color: "#d4d7d6" },
  "_css": { c: '\uE01D', color: "#519aba" },
  "_csv": { c: '\uE01E', color: "#8dc149" },
  "_cu": { c: '\uE01F', color: "#8dc149" },
  "_cu_1": { c: '\uE01F', color: "#a074c4" },
  "_d": { c: '\uE020', color: "#cc3e44" },
  "_dart": { c: '\uE021', color: "#519aba" },
  "_db": { c: '\uE022', color: "#f55385" },
  "_db_1": { c: '\uE022', color: "#519aba" },
  "_default": { c: '\uE023', color: "#d4d7d6" },
  "_docker": { c: '\uE025', color: "#519aba" },
  "_docker_1": { c: '\uE025', color: "#4d5a5e" },
  "_docker_2": { c: '\uE025', color: "#8dc149" },
  "_docker_3": { c: '\uE025', color: "#f55385" },
  "_ejs": { c: '\uE027', color: "#cbcb41" },
  "_elixir": { c: '\uE028', color: "#a074c4" },
  "_elixir_script": { c: '\uE029', color: "#a074c4" },
  "_elm": { c: '\uE02A', color: "#519aba" },
  "_eslint": { c: '\uE02C', color: "#a074c4" },
  "_eslint_1": { c: '\uE02C', color: "#4d5a5e" },
  "_ethereum": { c: '\uE02D', color: "#519aba" },
  "_f-sharp": { c: '\uE02E', color: "#519aba" },
  "_favicon": { c: '\uE02F', color: "#cbcb41" },
  "_firebase": { c: '\uE030', color: "#e37933" },
  "_firefox": { c: '\uE031', color: "#e37933" },
  "_font": { c: '\uE033', color: "#cc3e44" },
  "_git": { c: '\uE034', color: "#41535b" },
  "_github": { c: '\uE037', color: "#d4d7d6" },
  "_gitlab": { c: '\uE038', color: "#e37933" },
  "_go": { c: '\uE039', color: "#519aba" },
  "_go2": { c: '\uE03A', color: "#519aba" },
  "_godot": { c: '\uE03B', color: "#519aba" },
  "_godot_1": { c: '\uE03B', color: "#cc3e44" },
  "_godot_2": { c: '\uE03B', color: "#cbcb41" },
  "_godot_3": { c: '\uE03B', color: "#a074c4" },
  "_gradle": { c: '\uE03C', color: "#519aba" },
  "_grails": { c: '\uE03D', color: "#8dc149" },
  "_graphql": { c: '\uE03E', color: "#f55385" },
  "_grunt": { c: '\uE03F', color: "#e37933" },
  "_gulp": { c: '\uE040', color: "#cc3e44" },
  "_hacklang": { c: '\uE041', color: "#e37933" },
  "_haml": { c: '\uE042', color: "#cc3e44" },
  "_happenings": { c: '\uE043', color: "#519aba" },
  "_haskell": { c: '\uE044', color: "#a074c4" },
  "_haxe": { c: '\uE045', color: "#e37933" },
  "_haxe_1": { c: '\uE045', color: "#cbcb41" },
  "_haxe_2": { c: '\uE045', color: "#519aba" },
  "_haxe_3": { c: '\uE045', color: "#a074c4" },
  "_heroku": { c: '\uE046', color: "#a074c4" },
  "_hex": { c: '\uE047', color: "#cc3e44" },
  "_html": { c: '\uE048', color: "#519aba" },
  "_html_1": { c: '\uE048', color: "#8dc149" },
  "_html_2": { c: '\uE048', color: "#cbcb41" },
  "_html_3": { c: '\uE048', color: "#e37933" },
  "_html_erb": { c: '\uE049', color: "#cc3e44" },
  "_ignored": { c: '\uE04A', color: "#41535b" },
  "_illustrator": { c: '\uE04B', color: "#cbcb41" },
  "_image": { c: '\uE04C', color: "#a074c4" },
  "_info": { c: '\uE04D', color: "#519aba" },
  "_ionic": { c: '\uE04E', color: "#519aba" },
  "_jade": { c: '\uE04F', color: "#cc3e44" },
  "_java": { c: '\uE050', color: "#cc3e44" },
  "_java_1": { c: '\uE050', color: "#519aba" },
  "_javascript": { c: '\uE051', color: "#cbcb41" },
  "_javascript_1": { c: '\uE051', color: "#e37933" },
  "_javascript_2": { c: '\uE051', color: "#519aba" },
  "_jenkins": { c: '\uE052', color: "#cc3e44" },
  "_jinja": { c: '\uE053', color: "#cc3e44" },
  "_json": { c: '\uE055', color: "#cbcb41" },
  "_json_1": { c: '\uE055', color: "#8dc149" },
  "_julia": { c: '\uE056', color: "#a074c4" },
  "_karma": { c: '\uE057', color: "#8dc149" },
  "_kotlin": { c: '\uE058', color: "#e37933" },
  "_less": { c: '\uE059', color: "#519aba" },
  "_license": { c: '\uE05A', color: "#cbcb41" },
  "_license_1": { c: '\uE05A', color: "#e37933" },
  "_license_2": { c: '\uE05A', color: "#cc3e44" },
  "_liquid": { c: '\uE05B', color: "#8dc149" },
  "_livescript": { c: '\uE05C', color: "#519aba" },
  "_lock": { c: '\uE05D', color: "#8dc149" },
  "_lua": { c: '\uE05E', color: "#519aba" },
  "_makefile": { c: '\uE05F', color: "#e37933" },
  "_makefile_1": { c: '\uE05F', color: "#a074c4" },
  "_makefile_2": { c: '\uE05F', color: "#6d8086" },
  "_makefile_3": { c: '\uE05F', color: "#519aba" },
  "_markdown": { c: '\uE060', color: "#519aba" },
  "_maven": { c: '\uE061', color: "#cc3e44" },
  "_mdo": { c: '\uE062', color: "#cc3e44" },
  "_mustache": { c: '\uE063', color: "#e37933" },
  "_nim": { c: '\uE065', color: "#cbcb41" },
  "_notebook": { c: '\uE066', color: "#519aba" },
  "_npm": { c: '\uE067', color: "#41535b" },
  "_npm_1": { c: '\uE067', color: "#cc3e44" },
  "_npm_ignored": { c: '\uE068', color: "#41535b" },
  "_nunjucks": { c: '\uE069', color: "#8dc149" },
  "_ocaml": { c: '\uE06A', color: "#e37933" },
  "_odata": { c: '\uE06B', color: "#e37933" },
  "_pddl": { c: '\uE06C', color: "#a074c4" },
  "_pdf": { c: '\uE06D', color: "#cc3e44" },
  "_perl": { c: '\uE06E', color: "#519aba" },
  "_photoshop": { c: '\uE06F', color: "#519aba" },
  "_php": { c: '\uE070', color: "#a074c4" },
  "_pipeline": { c: '\uE071', color: "#e37933" },
  "_plan": { c: '\uE072', color: "#8dc149" },
  "_platformio": { c: '\uE073', color: "#e37933" },
  "_powershell": { c: '\uE074', color: "#519aba" },
  "_prisma": { c: '\uE075', color: "#519aba" },
  "_prolog": { c: '\uE077', color: "#e37933" },
  "_pug": { c: '\uE078', color: "#cc3e44" },
  "_puppet": { c: '\uE079', color: "#cbcb41" },
  "_purescript": { c: '\uE07A', color: "#d4d7d6" },
  "_python": { c: '\uE07B', color: "#519aba" },
  "_react": { c: '\uE07D', color: "#519aba" },
  "_react_1": { c: '\uE07D', color: "#e37933" },
  "_reasonml": { c: '\uE07E', color: "#cc3e44" },
  "_rescript": { c: '\uE07F', color: "#cc3e44" },
  "_rescript_1": { c: '\uE07F', color: "#f55385" },
  "_rollup": { c: '\uE080', color: "#cc3e44" },
  "_ruby": { c: '\uE081', color: "#cc3e44" },
  "_rust": { c: '\uE082', color: "#6d8086" },
  "_salesforce": { c: '\uE083', color: "#519aba" },
  "_sass": { c: '\uE084', color: "#f55385" },
  "_sbt": { c: '\uE085', color: "#519aba" },
  "_scala": { c: '\uE086', color: "#cc3e44" },
  "_shell": { c: '\uE089', color: "#8dc149" },
  "_slim": { c: '\uE08A', color: "#e37933" },
  "_smarty": { c: '\uE08B', color: "#cbcb41" },
  "_spring": { c: '\uE08C', color: "#8dc149" },
  "_stylelint": { c: '\uE08D', color: "#d4d7d6" },
  "_stylelint_1": { c: '\uE08D', color: "#4d5a5e" },
  "_stylus": { c: '\uE08E', color: "#8dc149" },
  "_sublime": { c: '\uE08F', color: "#e37933" },
  "_svelte": { c: '\uE090', color: "#cc3e44" },
  "_svg": { c: '\uE091', color: "#a074c4" },
  "_svg_1": { c: '\uE091', color: "#519aba" },
  "_swift": { c: '\uE092', color: "#e37933" },
  "_terraform": { c: '\uE093', color: "#a074c4" },
  "_tex": { c: '\uE094', color: "#519aba" },
  "_tex_1": { c: '\uE094', color: "#cbcb41" },
  "_tex_2": { c: '\uE094', color: "#e37933" },
  "_tex_3": { c: '\uE094', color: "#d4d7d6" },
  "_todo": { c: '\uE096', color: "#d4d7d6" },
  "_tsconfig": { c: '\uE097', color: "#519aba" },
  "_twig": { c: '\uE098', color: "#8dc149" },
  "_typescript": { c: '\uE099', color: "#519aba" },
  "_typescript_1": { c: '\uE099', color: "#e37933" },
  "_vala": { c: '\uE09A', color: "#6d8086" },
  "_video": { c: '\uE09B', color: "#f55385" },
  "_vite": { c: '\uE09C', color: "#cbcb41" },
  "_vue": { c: '\uE09D', color: "#8dc149" },
  "_wasm": { c: '\uE09E', color: "#a074c4" },
  "_wat": { c: '\uE09F', color: "#a074c4" },
  "_webpack": { c: '\uE0A0', color: "#519aba" },
  "_wgt": { c: '\uE0A1', color: "#519aba" },
  "_windows": { c: '\uE0A2', color: "#519aba" },
  "_word": { c: '\uE0A3', color: "#519aba" },
  "_xls": { c: '\uE0A4', color: "#8dc149" },
  "_xml": { c: '\uE0A5', color: "#e37933" },
  "_yarn": { c: '\uE0A6', color: "#519aba" },
  "_yml": { c: '\uE0A7', color: "#a074c4" },
  "_zig": { c: '\uE0A8', color: "#e37933" },
  "_zip": { c: '\uE0A9', color: "#cc3e44" },
  "_zip_1": { c: '\uE0A9', color: "#6d8086" },
}

export const FILE_DEFAULT = "_default"

export const FILE_NAMES: Record<string, string> = {
  "babel.config.cjs": "_babel",
  "babel.config.js": "_babel",
  "babel.config.json": "_babel",
  "bower.json": "_bower",
  "build": "_bazel",
  "build.bazel": "_bazel",
  "changelog": "_clock",
  "changelog.md": "_clock",
  "changelog.txt": "_clock",
  "changes": "_clock",
  "changes.md": "_clock",
  "changes.txt": "_clock",
  "cmakelists.txt": "_makefile_3",
  "compiling": "_license_1",
  "compiling.md": "_license_1",
  "compiling.txt": "_license_1",
  "contributing": "_license_2",
  "contributing.md": "_license_2",
  "contributing.txt": "_license_2",
  "copying": "_license",
  "copying.md": "_license",
  "copying.txt": "_license",
  "docker-healthcheck": "_docker_2",
  "eslint.config.js": "_eslint",
  "firebase.json": "_firebase",
  "geckodriver": "_firefox",
  "gruntfile.babel.js": "_grunt",
  "gruntfile.coffee": "_grunt",
  "gruntfile.js": "_grunt",
  "gulpfile": "_gulp",
  "gulpfile.js": "_gulp",
  "ionic.config.json": "_ionic",
  "ionic.project": "_ionic",
  "jenkinsfile": "_jenkins",
  "karma.conf.cjs": "_karma",
  "karma.conf.coffee": "_karma",
  "karma.conf.js": "_karma",
  "karma.conf.mjs": "_karma",
  "licence": "_license",
  "licence.md": "_license",
  "licence.txt": "_license",
  "license": "_license",
  "license.md": "_license",
  "license.txt": "_license",
  "mime.types": "_config",
  "mix": "_hex",
  "mvnw": "_maven",
  "npm-debug.log": "_npm_ignored",
  "omakefile": "_makefile_2",
  "platformio.ini": "_platformio",
  "pom.xml": "_maven",
  "procfile": "_heroku",
  "qmakefile": "_makefile_1",
  "readme": "_info",
  "readme.md": "_info",
  "readme.txt": "_info",
  "rollup.config.js": "_rollup",
  "sass-lint.yml": "_sass",
  "stylelint.config.cjs": "_stylelint",
  "stylelint.config.js": "_stylelint",
  "stylelint.config.mjs": "_stylelint",
  "swagger.json": "_json_1",
  "swagger.yaml": "_json_1",
  "swagger.yml": "_json_1",
  "todo": "_todo",
  "todo.md": "_todo",
  "todo.txt": "_todo",
  "tsconfig.json": "_tsconfig",
  "version": "_clock",
  "version.md": "_clock",
  "version.txt": "_clock",
  "vite.config.cjs": "_vite",
  "vite.config.cts": "_vite",
  "vite.config.js": "_vite",
  "vite.config.mjs": "_vite",
  "vite.config.mts": "_vite",
  "vite.config.ts": "_vite",
  "webpack.common.cjs": "_webpack",
  "webpack.common.js": "_webpack",
  "webpack.common.mjs": "_webpack",
  "webpack.common.ts": "_webpack",
  "webpack.config.build.cjs": "_webpack",
  "webpack.config.build.js": "_webpack",
  "webpack.config.build.mjs": "_webpack",
  "webpack.config.build.ts": "_webpack",
  "webpack.config.cjs": "_webpack",
  "webpack.config.js": "_webpack",
  "webpack.config.mjs": "_webpack",
  "webpack.config.ts": "_webpack",
  "webpack.dev.cjs": "_webpack",
  "webpack.dev.js": "_webpack",
  "webpack.dev.mjs": "_webpack",
  "webpack.dev.ts": "_webpack",
  "webpack.prod.cjs": "_webpack",
  "webpack.prod.js": "_webpack",
  "webpack.prod.mjs": "_webpack",
  "webpack.prod.ts": "_webpack",
  "workspace": "_bazel",
  "workspace.bazel": "_bazel",
  "yarn.clean": "_yarn",
  "yarn.lock": "_yarn",
}

export const FILE_EXTENSIONS: Record<string, string> = {
  "3dm": "_svg_1",
  "3ds": "_svg_1",
  "ad": "_argdown",
  "ai": "_illustrator",
  "apex": "_salesforce",
  "argdown": "_argdown",
  "article": "_go",
  "asax": "_html_2",
  "ascx": "_html_1",
  "asm": "_asm",
  "aspx": "_html",
  "avi": "_video",
  "avif": "_image",
  "babelrc": "_babel",
  "babelrc.cjs": "_babel",
  "babelrc.js": "_babel",
  "bazel": "_bazel",
  "bazelignore": "_bazel",
  "bazelrc": "_bazel_1",
  "bazelversion": "_bazel",
  "bicep": "_bicep",
  "bowerrc": "_bower",
  "bsl": "_bsl",
  "build": "_bazel",
  "bzl": "_bazel",
  "cake": "_cake",
  "cer": "_lock",
  "cert": "_lock",
  "cfc": "_coldfusion",
  "cfm": "_coldfusion",
  "cjs.map": "_javascript",
  "cjsx": "_react",
  "class": "_java_1",
  "classpath": "_java",
  "cls": "_salesforce",
  "cmx": "_ocaml",
  "cmxa": "_ocaml",
  "codeclimate.yml": "_code-climate",
  "component": "_html_3",
  "config": "_config",
  "cr": "_crystal",
  "crt": "_lock",
  "cson": "_json",
  "css.map": "_css",
  "csv": "_csv",
  "ctp": "_cake_php",
  "cuh": "_cu_1",
  "d": "_d",
  "dae": "_svg_1",
  "direnv": "_config",
  "doc": "_word",
  "dockerignore": "_docker_1",
  "docx": "_word",
  "ds_store": "_ignored",
  "dtx": "_tex_2",
  "ecr": "_crystal_embedded",
  "edn": "_clojure_1",
  "ejs": "_ejs",
  "elm": "_elm",
  "eot": "_font",
  "epp": "_puppet",
  "erb": "_html_erb",
  "erb.html": "_html_erb",
  "es": "_javascript",
  "es5": "_javascript",
  "es7": "_javascript",
  "eslintignore": "_eslint_1",
  "eslintrc": "_eslint",
  "eslintrc.cjs": "_eslint",
  "eslintrc.js": "_eslint",
  "eslintrc.json": "_eslint",
  "eslintrc.yaml": "_eslint",
  "eslintrc.yml": "_eslint",
  "ex": "_elixir",
  "exs": "_elixir_script",
  "firebaserc": "_firebase",
  "flac": "_audio",
  "gd": "_godot",
  "gif": "_image",
  "gitattributes": "_git",
  "gitconfig": "_git",
  "github-issues": "_github",
  "gitkeep": "_git",
  "gitlab-ci.yml": "_gitlab",
  "gitmodules": "_git",
  "godot": "_godot_1",
  "gql": "_graphql",
  "gradle": "_gradle",
  "graphql": "_graphql",
  "graphqls": "_graphql",
  "gsp": "_grails",
  "h": "_c_1",
  "h++": "_cpp_1",
  "hack": "_hacklang",
  "haml": "_haml",
  "happenings": "_happenings",
  "hh": "_cpp_1",
  "hpp": "_cpp_1",
  "hs": "_haskell",
  "htaccess": "_config",
  "html.erb": "_html_erb",
  "hu": "_cu_1",
  "hx": "_haxe",
  "hxml": "_haxe_3",
  "hxp": "_haxe_2",
  "hxs": "_haxe_1",
  "hxx": "_cpp_1",
  "ico": "_favicon",
  "ins": "_tex_3",
  "ipynb": "_notebook",
  "jade": "_jade",
  "jar": "_zip",
  "jinja": "_jinja",
  "jinja2": "_jinja",
  "jpeg": "_image",
  "jpg": "_image",
  "js.map": "_javascript",
  "jscsrc": "_javascript_2",
  "jshintrc": "_javascript_2",
  "key": "_lock",
  "kt": "_kotlin",
  "kts": "_kotlin",
  "lhs": "_haskell",
  "liquid": "_liquid",
  "litcoffee": "_coffee",
  "ls": "_livescript",
  "master": "_html_2",
  "mdo": "_mdo",
  "mjs.map": "_javascript",
  "ml": "_ocaml",
  "mli": "_ocaml",
  "mov": "_video",
  "mp3": "_audio",
  "mp4": "_video",
  "mpg": "_video",
  "mustache": "_mustache",
  "nim": "_nim",
  "nims": "_nim",
  "nj": "_nunjucks",
  "njk": "_nunjucks",
  "njs": "_nunjucks",
  "npm-debug.log": "_npm",
  "npmignore": "_npm_1",
  "npmrc": "_npm_1",
  "nunj": "_nunjucks",
  "nunjs": "_nunjucks",
  "nunjucks": "_nunjucks",
  "obj": "_svg_1",
  "odata": "_odata",
  "ogg": "_audio",
  "ogv": "_video",
  "otf": "_font",
  "pddl": "_pddl",
  "pdf": "_pdf",
  "pem": "_lock",
  "php.inc": "_php",
  "pipeline": "_pipeline",
  "plan": "_plan",
  "png": "_image",
  "pp": "_puppet",
  "prisma": "_prisma",
  "pro": "_prolog",
  "psd": "_photoshop",
  "purs": "_purescript",
  "pxm": "_image",
  "r": "_R",
  "re": "_reasonml",
  "res": "_rescript",
  "resi": "_rescript_1",
  "rmd": "_R",
  "s": "_asm",
  "sass": "_sass",
  "sbt": "_sbt",
  "scala": "_scala",
  "slang": "_crystal_embedded",
  "slide": "_go",
  "slim": "_slim",
  "slugignore": "_config",
  "smarty.tpl": "_smarty",
  "sol": "_ethereum",
  "soql": "_db_1",
  "spec.cjs": "_javascript_1",
  "spec.js": "_javascript_1",
  "spec.jsx": "_react_1",
  "spec.mjs": "_javascript_1",
  "spec.ts": "_typescript_1",
  "spec.tsx": "_react_1",
  "springbeans": "_spring",
  "sss": "_css",
  "stache": "_mustache",
  "static": "_config",
  "stl": "_svg_1",
  "styl": "_stylus",
  "stylelintignore": "_stylelint_1",
  "stylelintrc": "_stylelint",
  "stylelintrc.js": "_stylelint",
  "stylelintrc.json": "_stylelint",
  "stylelintrc.yaml": "_stylelint",
  "stylelintrc.yml": "_stylelint",
  "sublime-project": "_sublime",
  "sublime-workspace": "_sublime",
  "svelte": "_svelte",
  "svg": "_svg",
  "svgx": "_image",
  "test.cjs": "_javascript_1",
  "test.js": "_javascript_1",
  "test.jsx": "_react_1",
  "test.mjs": "_javascript_1",
  "test.ts": "_typescript_1",
  "test.tsx": "_react_1",
  "tf": "_terraform",
  "tf.json": "_terraform",
  "tfvars": "_terraform",
  "tfvars.json": "_terraform",
  "tiff": "_image",
  "tmp": "_clock_1",
  "toml": "_config",
  "tpl": "_smarty",
  "tres": "_godot_2",
  "tscn": "_godot_3",
  "ttf": "_font",
  "twig": "_twig",
  "vala": "_vala",
  "vapi": "_vala",
  "vue": "_vue",
  "wasm": "_wasm",
  "wat": "_wat",
  "wav": "_audio",
  "webm": "_video",
  "webp": "_image",
  "wgt": "_wgt",
  "woff": "_font",
  "woff2": "_font",
  "workspace": "_bazel",
  "xls": "_xls",
  "xlsx": "_xls",
  "zig": "_zig",
  "zip": "_zip_1",
}

export const LANGUAGE_IDS: Record<string, string> = {
  "argdown": "_argdown",
  "bat": "_windows",
  "bicep": "_bicep",
  "blade": "_php",
  "c": "_c",
  "chatagent": "_markdown",
  "clojure": "_clojure",
  "coffeescript": "_coffee",
  "cpp": "_cpp",
  "csharp": "_c-sharp",
  "css": "_css",
  "cuda-cpp": "_cu",
  "dart": "_dart",
  "django-html": "_html_3",
  "dockercompose": "_docker_3",
  "dockerfile": "_docker",
  "dotenv": "_config",
  "elixir": "_elixir",
  "elm": "_elm",
  "erb": "_html_erb",
  "fsharp": "_f-sharp",
  "git-commit": "_git",
  "github-issues": "_github",
  "go": "_go2",
  "godot": "_godot",
  "gradle": "_gradle",
  "groovy": "_grails",
  "haml": "_haml",
  "handlebars": "_mustache",
  "haskell": "_haskell",
  "haxe": "_haxe",
  "html": "_html_3",
  "ignore": "_git",
  "instructions": "_markdown",
  "jade": "_pug",
  "java": "_java",
  "javascript": "_javascript",
  "javascriptreact": "_react",
  "jinja": "_jinja",
  "json": "_json",
  "jsonc": "_json",
  "jsonl": "_json",
  "julia": "_julia",
  "kotlin": "_kotlin",
  "latex": "_tex",
  "less": "_less",
  "lua": "_lua",
  "makefile": "_makefile",
  "markdown": "_markdown",
  "mustache": "_mustache",
  "nunjucks": "_nunjucks",
  "objective-c": "_c_2",
  "objective-cpp": "_cpp_2",
  "ocaml": "_ocaml",
  "perl": "_perl",
  "php": "_php",
  "postcss": "_css",
  "powershell": "_powershell",
  "prompt": "_markdown",
  "properties": "_config",
  "python": "_python",
  "r": "_R",
  "razor": "_html",
  "rescript": "_rescript",
  "ruby": "_ruby",
  "rust": "_rust",
  "sass": "_sass",
  "scss": "_sass",
  "search-result": "_code-search",
  "shellscript": "_shell",
  "skill": "_markdown",
  "sql": "_db",
  "stylus": "_stylus",
  "swift": "_swift",
  "terraform": "_terraform",
  "tex": "_tex_1",
  "todo": "_todo",
  "typescript": "_typescript",
  "typescriptreact": "_react",
  "vala": "_vala",
  "vue": "_vue",
  "xml": "_xml",
  "yaml": "_yml",
}
